### ISSUE TITLE
Reconsider public transportation mapping

### ISSUE THREAD

**Issue by goteusz-maszyk** [openstreetmap-ng/openstreetmap-ng#107]
_Part of #44_

I think everyone who has tried mapping public transport in OSM knows that. The current solution CANNOT be continued. Even with relatify, this is very unreliable and time consuming. Today, most agencies are providing their GTFS, which can be utilised for usage for everyone.

The best solution I've come up so far is to rip down all lines (not stops!) that are GTFS-able, which only leaves us some local "village buses" not covered. Those lines can still be mapped using current solution. This would obviously require us to create another way to get data, right?

My suggestion is to make:

**Public transportation API** Available at `/api/0.7/transit/`. Endpoints:
`/stop/<nodeid>` - returns information about all lines going through specified stop and their departure schedule.
`/line/<line_id>` - the line ID would be given in stop information, the endpoint returns lines stop list and shape.
But how would we get this information? Well.. there is a service https://mobilitydatabase.org/. They provide official GTFS feeds from around the world.

With this, OSM will also be able to have realtime transit data using GTFS realtime.

I leave this issue as a place for discussion, my idea is definitely not perfect and requires some improvements.

**Comment by Zaczero** [comment]
Here are my quick thoughts. This does not sound like something the OSM website should implement. Like many features on OSM, there should be dedicated tagging for these kinds of rules, and then we should have a dedicated service running that would filter and parse such tagging to provide a user-friendly API interface.

I admit this is an essential service for OpenStreetMap to have. I would rather see it as a gtfs.osm.org kind of thing (like nominatim.osm.org) and not www.osm.org.

**Comment by Zaczero** [comment]
I think it's safe to close this discussion for now.
