### ISSUE TITLE
Aerial imagery layer

### ISSUE THREAD

**Issue by goteusz-maszyk** [openstreetmap-ng/openstreetmap-ng#122]
It'd be awesome to utilize the aerial imagery used in iD to add another layer. No more login required to view real images :tada:

**Comment by Zaczero** [comment]
And perhaps even an aerial layer with a semi-transparent Carto overlay.

The goal is to:
- Find an aerial layer provider (Bing? Need to check the license)
- Add it to the layers list
- When the aerial layer is active, Carto is displayed on top of it (semi-transparently)

Once this issue is complete, we can consider implementing region-specific imagery, like Geoportal, etc.

**Comment by starsep** [comment]
For list of imagery https://github.com/osmlab/editor-layer-index can be used

**Comment by Aury88** [comment]
> The goal is to:
> 
>     * Find an aerial layer provider (Bing? Need to check the license)

> Once this issue is complete, we can consider implementing region-specific imagery, like Geoportal, etc.
I would tend to exclude bing from being a viable solution. the use of Bing aerial layer needed a specific grant from microsoft for the usage in osm. that grant was only limited to the use inside osm editing tool( behind a login) there is not any agreement about displaying bing layer to the consumer. also displaying bing layer, directly on the website, outside the editing tool  could be seen as a concurrent service to the microsoft bing map service.

[Mapbox](https://www.mapbox.com/contact/sales) esri and maptiler seem  more viable solutions but probably they  require a payment given the fact the usually sell their map/layer service

you can use lowres global maptiler layer but you will need probably to self host the data (527.2 GiB  for a 15-20m/pixel resolution)(see [here](https://data.maptiler.com/downloads/dataset/satellite-2021/#0.22/0/0), [here](https://documentation.maptiler.com/hc/en-us/articles/4413738104849-Satellite-2021-distribution) and [here](https://www.maptiler.com/satellite/#self-hosting))

I would also try for a joint venture with OpenAerialMap (OAM) ... their tiles are usually in highres but very limited to small portion of the globe, so i joint venture would help both to/and share effort with another open project...

**Comment by Zaczero** [comment]
I have assigned bounties for this issue. Thank you all for your input on this great new feature!
