### ISSUE TITLE
Include changeset in "history" tab, only if it contains change in displayed area

### ISSUE THREAD

**Issue by papryczk** [openstreetmap-ng/openstreetmap-ng#135]
I'm not sure whether someone already asked about that, but I frequently use OSM's history feature in order to monitor my area for recent changes. However the list is usually clustered with changesets, which spread around the world or region, without changing anything in the viewed portion of the map. Would it be possible to include on the list only changesets, that edit something on the viewed part of the map?

**Comment by Zaczero** [comment]
OSM-NG already supports multiple changesets bounding boxes which mostly eliminates this issue 😎. They are managed automatically with a simple change clustering algorithm.

**Comment by Zaczero** [comment]
I will close down this issue as there is no further discussion and there is no work to be done. OpenStreetMap-NG already works as you described :+1:.
