### ISSUE TITLE
Tags diff mode

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-ng/openstreetmap-ng#16]
Optionally display tag diffs on elements. Use color codings.

![image](https://github.com/Zaczero/openstreetmap-ng/assets/10835147/99ce4fde-8127-4e4a-8f03-53673db6163a)

The goal is to:

- Display color coded tag changes in element history view, enabled by default
- Show a button on the element page, when clicked, it modifies the tag list to be color-coded without page reload
- Colors should not be too distracting

**Comment by starsep** [comment]
Would something like that work?
| Before | After|
| - | - |
| ![image](https://github.com/Zaczero/openstreetmap-ng/assets/2798728/7ab8f554-6b4f-46bc-9e43-829eb7018392) | ![image](https://github.com/Zaczero/openstreetmap-ng/assets/2798728/91f4d630-c215-48c3-b1c8-b6a678d17142) |

White (no color): tag unchanged
Green: new tag in a version
Yellow: value of tag modified
Red: tag removed

I am not sure whether it makes sense to keep removed tag in next version.

**Comment by Zaczero** [comment]
The color schema is really good :+1: What if we make the green match the OSM theme green (tip: $green), for consistency and reduce opacity/make it lighter because it "pops" too much (transparentize/tint-color methods are useful for this).

> I am not sure whether it makes sense to keep removed tag in next version.

I think it looks fine but the delete line makes it somewhat difficult to read. Instead maybe slightly reduce text opacity of deleted rows and prefix keys with a dark-gray trash icon? (perhaps https://icons.getbootstrap.com/icons/trash-fill/). It makes sense to always show deleted tags after existing tags.

**Comment by Dimitar5555** [comment]
[better-osm-org script](https://github.com/deevroman/better-osm-org) also has such functionality. The colours look better when they are more saturated. Also the yellow is applied only to the value cell (since the key hasn't changed). Only changed tags are shown (which seems like a minus for me). For nodes it shows the moved distance and for other elements marks the elements if there has been a geometry change.

![image](https://github.com/Zaczero/openstreetmap-ng/assets/19364673/5399e9a5-8ce0-44de-ac74-dc40b946b1d4)
![image](https://github.com/Zaczero/openstreetmap-ng/assets/19364673/7f303100-702c-4530-b059-838829a04e45)

**Comment by Zaczero** [comment]
> Also the yellow is applied only to the value cell

It's a good idea

> For nodes it shows the moved distance and for other elements marks the elements if there has been a geometry change.

I'll note that down but we will create a separate issue and bounty for it, this one should focus on just tags :slightly_smiling_face:!

**Comment by Aury88** [comment]
is it possible to use the same color scheme to highlight changes in geometry/positions?
this could be applied to single nodes and their coordinates  in the node list of an element 

- yellow for changed in coordinate of already existing node 
- red for removed nodes,
- green for added nodes
- blue on white backgroud for unchanged nodes

**Comment by Zaczero** [comment]
@Aury88 yup #7

**Comment by Zaczero** [comment]
The feature has been merged and it looks amazing! Thank you all for your contribution on this issue.

I have decided to reward @starsep and @Dimitar5555 with 3$ bonus bounties - so 26$ payout in total.

@Dimitar5555 Since this is your first bounty, you can keep collecting the funds and let me know whenever you would like to withdraw. It's tracked [here](https://github.com/Zaczero/openstreetmap-ng/wiki/Ledger).

![Peek 2024-10-04 05-55](https://github.com/user-attachments/assets/43d20c3d-7139-4ad4-a171-c9e995ac2744)

<img src="https://github.com/user-attachments/assets/8a2d5288-8b03-466e-a93e-768d3788d684" width=450>
