### ISSUE TITLE
Reimplement map context menu

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-ng/openstreetmap-ng#27]
Some initial work has already been done.

![image](https://github.com/Zaczero/openstreetmap-ng/assets/10835147/67250777-54ad-44b9-a896-369281bfc84b)

**Comment by Playzinho** [comment]
![image](https://github.com/Zaczero/openstreetmap-ng/assets/77340463/ae3c9fa7-8b78-4c53-a987-3369c1bee20a)
for comparison with google maps
maybe add:
- coordinates
- add a missing location
- report a problem

The last two options need to be worked on better

**Comment by Zaczero** [comment]
Image from Discord

![image](https://github.com/Zaczero/openstreetmap-ng/assets/10835147/0aab122b-0e3f-4a7b-bb02-302e9a2bfc31)
