### ISSUE TITLE
Prehash login passwords on client-side before sending them

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-ng/openstreetmap-ng#4]
This will introduce a new safeguard against potentially compromised server. By having strong client-side hashing step, we could reduce server-side hash complexity and save on resources.

**Comment by Zaczero** [comment]
```py
@staticmethod
    def client_prehash(password: PasswordStr) -> str:
        """
        Prehash a password using the client's algorithm.
        """
        return pbkdf2_hmac(
            hash_name='sha256',
            password=password.get_secret_value().encode(),
            salt=b'',
            iterations=20_000,
        ).hex()
```

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveBits#browser_compatibility

**Comment by lightonflux** [comment]
Just out of interest: what is the reasoning behind introducing this feature? Safeguard users that use the same password for OSM and other services? Otherwise, I don't see any advantage. Thanks.

**Comment by Zaczero** [comment]
Hey, sure:
1. By moving some of the work to the client-side, the server becomes more lightweight and consumes fewer resources. We can lower the server-side hash time without compromising on password security.
2. We can remove any restrictions on password length, since the client-side hash produced is always the same size regardless of the original password's length. Previously, extremely long passwords would result in higher CPU usage on the server. Now, all passwords take the same amount of server processing time, no matter their size.
3. It helps prevent accidental password leakage (e.g., in server logs). Even if the server is misconfigured, clients have proof that their password will never be exposed.
4. With configurable client-side password hashing, we can allow users to adjust their [password iteration count](https://bitwarden.com/help/what-encryption-is-used/#changing-kdf-iterations) setting without impacting server-side performance. (Note: This feature is not yet implemented).
