### ISSUE TITLE
Profile picture background image

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-ng/openstreetmap-ng#43]
Part of #44

![image](https://github.com/Zaczero/openstreetmap-ng/assets/10835147/8806130a-4807-4cbe-afc8-24039042179e)

The goal is to:
- On profile page, when looking at the current user, show edit button in top right corner of the background bar
- The edit button works very similar to existing avatar image edit
- It is possible to remove background image after it's set
- There is some kind of information hinting that the edit button is for background image

The final result should be similar to:

![image](https://github.com/Zaczero/openstreetmap-ng/assets/10835147/01ee2d3c-de14-4c93-8d10-437d2bed74bb)

**Comment by kkalata** [comment]
[I started working on it.](https://github.com/kkalata/openstreetmap-ng/tree/profile_background)

**Comment by Zaczero** [comment]
Sure! If you need any help hit me up on Discord.

**Comment by Zaczero** [comment]
![2024-08-09 20-31-42-0002](https://github.com/user-attachments/assets/def35bac-79e8-45f7-b68a-818f1121960c)
