### ISSUE TITLE
Implement activity chart

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-ng/openstreetmap-ng#47]
Part of #44 

![image](https://github.com/Zaczero/openstreetmap-ng/assets/10835147/ae27cb69-04d7-42bb-a510-99fd63a01bd7)

The goal is to:
- Implement the activity chart displayed on user profiles
- Remove the placeholder image

**Comment by tomekrzymyszkiewicz** [comment]
Is it preffered to use external library or prepare someting tailored? I would consider using [cal-heatmap](https://github.com/wa0x6e/cal-heatmap) or [july](https://github.com/e-hulten/july). cal-heatmap looks better (more GitHub style) but choosing july will be better if we want to stick to Python.

**Comment by Zaczero** [comment]
I don't think this is complex enough to require a library. Here's how I see it:

1. Get day-by-day activity number for past year
2. Get 90th (or 95th) percentile to hide activity outliers
3. Scale activity to 0-1 (values above 1 are clamped down to 1) and assign colors from white to green, [this algorithm](https://github.com/twbs/bootstrap/blob/d2d4581790da2618d3fe063dafaa6205c73aabdd/scss/_functions.scss#L206-L208) will look perfect
4. Format and display data in HTML template
5. Write some JS to handle hover events and change details text

Tip: numpy array will work super efficient for it. It also provides necessary percentile methods.

**Comment by KonradowyPL** [comment]
I can do the frontend

**Comment by Zaczero** [comment]
@KonradowyPL Great! You will certainly work on top of [those changes](https://github.com/Zaczero/openstreetmap-ng/pull/65). We are just waiting for small PR changes. I'll create a team on Discord so we can communicate quickly. We don't want to reinvent the wheel with the design - let's just make it work as it does on other sites (neis, github, etc.)
