### ISSUE TITLE
Migrate changesets history RSS feeds

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-ng/openstreetmap-ng#61]
The goal is to replicate the behavior of:
- https://www.openstreetmap.org/history/feed
- https://www.openstreetmap.org/user/NorthCrab/history/feed

Additional requirements:
- The code should reuse parts of existing HTML responses (without the */feed* suffix): querying, filtering, etc.
- The data formatting should be contained in app/format/api06_changeset_rss.py file
- Take inspiration from api06_note_rss.py

**Comment by tomekrzymyszkiewicz** [comment]
I've read how the note RSS feed is created, and I will try to implement that for changesets.
