### ISSUE TITLE
pytest from different directory fails due to relative paths

### ISSUE THREAD

**Issue by starsep** [openstreetmap-ng/openstreetmap-ng#84]
1. Go to non-root directory of the project. Example: `cd app`.
2. Run `pytest`

Expected: tests are run correctly
Actual: tests fail due to relative resource `Path`s.

```
==================================================================== ERRORS ====================================================================
________________________________________________ ERROR collecting app/services/test_service.py _________________________________________________
services/test_service.py:9: in <module>
    from app.lib.auth_context import auth_context
lib/auth_context.py:11: in <module>
    from app.models.db.user import User
models/db/user.py:20: in <module>
    from app.lib.avatar import Avatar
lib/avatar.py:23: in <module>
    class Avatar:
lib/avatar.py:24: in Avatar
    default_image: bytes = Path('./app/static/img/avatar.webp').read_bytes()
/nix/store/pi4y0i02klddf4g1g6l9n2gk9avzxdh8-python/lib/python3.12/pathlib.py:1019: in read_bytes
    with self.open(mode='rb') as f:
/nix/store/pi4y0i02klddf4g1g6l9n2gk9avzxdh8-python/lib/python3.12/pathlib.py:1013: in open
    return io.open(self, mode, buffering, encoding, errors, newline)
E   FileNotFoundError: [Errno 2] No such file or directory: 'app/static/img/avatar.webp'
=========================================================== short test summary info ============================================================
ERROR services/test_service.py - FileNotFoundError: [Errno 2] No such file or directory: 'app/static/img/avatar.webp'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
1 error in 1.11s
```

Relevant line: https://github.com/openstreetmap-ng/openstreetmap-ng/blob/bdbc0cfdb77866b5746f823f56a35b691ec15149/app/lib/avatar.py#L24

One way of solving it would be adding to some file which wouldn't be moved for example `TEST_ROOT = Path(__file__)` and then using `Path(TEST_ROOT, '../app/static/img/avatar.webp')` so relative to chosen file.

PS I found it by running single test from IntelliJ IDE: then pytest is run from directory where test is located.

**Comment by Zaczero** [comment]
About the IntelliJ testing, is it possible for you to prepare a workspace configuration that will change the tests work directory? [It seems to be possible](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000658159-Project-root-as-default-working-directory). It looks like this is only the default behavior. Fixing this in the project will be unnecessarily complex.

**Comment by starsep** [comment]
Workaround works but with issues:
1. Macros `$ContentRoot$` and  `$ProjectFileDir$` didn't work for me. I had to put project's path into template
2. Template which needs to be modified is Python tests -> Autodetect. **Not pytest**
![image](https://github.com/openstreetmap-ng/openstreetmap-ng/assets/2798728/54e25511-e417-4d2a-a07f-5e2bc20413fd)


I think the solution I suggested should be *relatively* easy. 
Maybe putting `APP_ROOT = Path(__file__).parent` in `tests/__init__.py`?
I can contribute it if such approach sounds alright.

**Comment by Zaczero** [comment]
Seems like there is a very easy fix using [os.chdir](https://note.nkmk.me/en/python-os-getcwd-chdir/). I'll do that alongside nix dir improvements (I'll make it use the same variable). Thanks for the help and I'll let you know when the fix is ready for testing! :+1:

**Comment by Zaczero** [comment]
Fixed. With Nix, I resolved it by creating a custom function that always cds into the project directory before running further commands, which helps keep the code clean. As a bonus, I was able to conveniently integrate ShellCheck for shell scripts, which will validate all scripts and print helpful errors like these:

![image](https://github.com/openstreetmap-ng/openstreetmap-ng/assets/10835147/022e41a1-426c-4acd-bd31-fd0ab0c2c2c6)
