### ISSUE TITLE
Link to Relatify when viewing a public transport relation

### ISSUE THREAD

**Issue by FloEdelmann** [openstreetmap-ng/openstreetmap-ng#89]
[Relatify](https://relatify.monicz.dev/) is a useful public transport relation editor. It would be useful to link to it when viewing those relations.

**Comment by KonradowyPL** [comment]
I suggest that the "Edit" button could have option to edit in realify when viewing public transport relations

**Comment by starsep** [comment]
> I suggest that the "Edit" button could have option to edit in realify when viewing public transport relations

That's should be easy to implement.

My concern is UX: it might be confusing that sometimes missing Relatify from list of available editors.
We could be having Relatify always visible but inactive (greyed out).

Another issue is that adding more specialized editors will make list very long.
There is no clear policy of inclusion of editors in the current website which already have caused backlash in the community.

**Comment by Zaczero** [comment]
I share the concern that adding specialized editors will make the selection too messy. I was thinking we could implement an official recommend software page (#24) with a dedicated section for specialized editors. This software discovery issue affects a broad range of applications, so we may as well do it once and well. What do you think?

**Comment by FloEdelmann** [comment]
Sounds good. The "Edit" menu could then link to that section from every page to make it more discoverable.

(Feel free to close this issue if you prefer to keep everything in #24.)

**Comment by Zaczero** [comment]
Okay, I shortly summarized the idea there and we'll do it as a part of the recommend software page!
