### ISSUE TITLE
Improve theme of geolocation icon

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap-ng/openstreetmap-ng#93]
![image](https://github.com/user-attachments/assets/8502f0b2-241f-4214-b10e-1896ac5b397a)

Currently the icon feels a bit out of place because it's too thin.

One idea would be to try out https://www.svgrepo.com/svg/399143/location-on and perhaps round its edges:

![image](https://github.com/user-attachments/assets/15668da4-19af-42ee-a67f-f4361ecb37f3)

**Comment by kkalata** [comment]
I made my own icon, which tries to match the current style. Be aware, that the PNG icon (for reviewing purposes, just under here) is black on transparent, and the SVG icon is white on transparent.
![locate](https://github.com/user-attachments/assets/22fdf955-a814-4c1a-85a7-61218ced8e1f)
[SVG icon](https://github.com/user-attachments/assets/e4df3a50-d338-4631-b917-742496d3dac9)
![leaflet-controls](https://github.com/user-attachments/assets/d27569ca-0c17-4459-b208-68a7b81ffe0c)

**Comment by Zaczero** [comment]
We shouldn't use sprite files anymore—they are a thing of the past. I have [pushed a commit](https://github.com/openstreetmap-ng/openstreetmap-ng/commit/700e1d6b3748042cb4cddbfb4fefcf8c834adcb2) to use the new icon. I am currently working on a separate branch.
