### ISSUE TITLE
Found locale names without localization data

### ISSUE THREAD

**Issue by starsep** [openstreetmap-ng/openstreetmap-ng#95]
After https://github.com/openstreetmap-ng/openstreetmap-ng/commit/91e9dab9b4a6e0167bfd2f8c0abf7c3af22c07ce

I see this warning
> WARNING:  | 2024-07-26 16:53:00 | root Found locale names without localization data: ['aa', 'ae', 'ak', 'am', 'av', 'ay', 'bh', 'bm', 'ch', 'co', 'cr', 'dz', 'ee', 'ff', 'fj', 'ho', 'hz', 'ii', 'ik', 'iu', 'jv', 'kg', 'ki', 'kk', 'kl', 'kr', 'ks', 'ku', 'kv', 'kw', 'lg', 'lo', 'lu', 'mh', 'mi', 'mn', 'mt', 'na', 'nd', 'ng', 'no', 'nr', 'nv', 'ny', 'oj', 'pi', 'pt-BR', 'rn', 'sg', 'sm', 'sn', 'ss', 'st', 'tg', 'tn', 'to', 'ts', 'ty', 'ug', 've', 'wa', 'xh', 'zu']

If I understand correctly that's list of languages from config/locale/names.json which are not in config/locale/i18next/map.json.
Is there something I can do as a programmer not speaking those languages?

**Comment by Zaczero** [comment]
Warning is not a good message type here, [I changed it to info](https://github.com/openstreetmap-ng/openstreetmap-ng/commit/081c8cd03d555d8bf7d5ac6b3f72fcb0f074ec8e). The idea is to inform that the following locales exist in names.json but have no dedicated localization data. And this is fine.
