### ISSUE TITLE
 "fromBounds is null" while creating route

### ISSUE THREAD

**Issue by KonradowyPL** [openstreetmap-ng/openstreetmap-ng#96]
## How to reproduce?
1. click "directions" button
2. select two points
3. click "go"
4. refresh website a couple of times
5. you will see error "Failed to submit standard form TypeError: fromBounds is null"
![image](https://github.com/user-attachments/assets/22c5c0e1-bd8c-4b82-9a2f-93cc82fdb20f)

browser: Mozilla/5.0  Firefox/127.0

example url: http://127.0.0.1:8000/directions?route=50.27219%2C19.03455%3B50.27011%2C19.03392

and btw clicking reverse directions two times fixes issue

**Comment by Zaczero** [comment]
Thank You! That's a really good catch! I have assigned you a small bonus bounty for it :slightly_smiling_face:

**Comment by KonradowyPL** [comment]
Its weird. Now refreshing works, but after using `ctrl`+`f5`  markers are no longer visible. Clicking reverse button does not slove the issue. There are no console errors.

**Comment by Zaczero** [comment]
> Now refreshing works, but pressing `ctrl`+`f5` or clicking link still bugs out the form. Clicking reverse button does not solve the issue. There are no console errors.

To summarize, we agreed on Discord that this was the result of some local development changes, not related to the original issue. The original fix was enough to resolve it.
